package startup

import (
	"time"
)

// CreateDefaultStartupWorkflow 创建默认启动工作流
func CreateDefaultStartupWorkflow() *StartupWorkflow {
	return &StartupWorkflow{
		ID:          "xiaozhi-flow-default-startup",
		Name:        "XiaoZhi Flow 默认启动工作流",
		Description: "将现有的bootstrap启动步骤转换为可视化工作流",
		Version:     "1.0.0",
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		Tags:        []string{"default", "system", "startup"},
		Config: StartupWorkflowConfig{
			Timeout:       DefaultTimeout,
			MaxRetries:    DefaultMaxRetries,
			ParallelLimit: DefaultParallelLimit,
			EnableLog:     true,
			Environment:   make(map[string]interface{}),
			Variables:     make(map[string]interface{}),
			OnFailure:     FailureActionStop,
		},
		Nodes: []StartupNode{
			{
				ID:        "storage:init-config-store",
				Name:      "初始化配置存储",
				Type:      StartupNodeStorage,
				Description: "初始化配置存储系统，用于持久化应用配置",
				DependsOn: []string{},
				Config: map[string]interface{}{
					"storage_type": "file",
					"config_path": "config/",
				},
				Status:    workflow.NodeStatusPending,
				Timeout:   30 * time.Second,
				Critical:  true,
				Position: workflow.Position{X: 100, Y: 100},
				Metadata: map[string]string{
					"step_number": "1",
					"category":   "storage",
					"bootstrap_id": "storage:init-config-store",
				},
			},
			{
				ID:        "storage:init-database",
				Name:      "初始化数据库",
				Type:      StartupNodeStorage,
				Description: "初始化数据库连接，支持SQLite、MySQL、PostgreSQL",
				DependsOn: []string{"storage:init-config-store"},
				Config: map[string]interface{}{
					"database_type": "sqlite",
					"connection_string": "./data/xiaozhi.db",
					"auto_migrate": true,
					"w_mode":      true,
				},
				Status:    workflow.NodeStatusPending,
				Timeout:   60 * time.Second,
				Critical:  true,
				Position: workflow.Position{X: 300, Y: 100},
				Metadata: map[string]string{
					"step_number": "2",
					"category":   "storage",
					"bootstrap_id": "storage:init-database",
				},
			},
			{
				ID:        "config:load-default",
				Name:      "加载默认配置",
				Type:      StartupNodeConfig,
				Description: "从数据库加载默认配置，如果没有则使用内置默认值",
				DependsOn: []string{"storage:init-config-store", "storage:init-database"},
				Config: map[string]interface{}{
					"config_file": "default_config.json",
					"fallback_to_defaults": true,
				},
				Status:    workflow.NodeStatusPending,
				Timeout:   30 * time.Second,
				Critical:  true,
				Position: workflow.Position{X: 500, Y: 100},
				Metadata: map[string]string{
					"step_number": "3",
					"category":   "config",
					"bootstrap_id": "config:load-default",
				},
			},
			{
				ID:        "logging:init-provider",
				Name:      "初始化日志系统",
				Type:      StartupNodeService,
				Description: "初始化日志提供者，设置日志级别和输出格式",
				DependsOn: []string{"config:load-default"},
				Config: map[string]interface{}{
					"log_level": "info",
					"log_dir":   "logs/",
					"log_file":  "xiaozhi-server.log",
					"max_size":  "100MB",
					"max_backups": 10,
					"compress": true,
				},
				Status:    workflow.NodeStatusPending,
				Timeout:   20 * time.Second,
				Critical:  false,
				Position: workflow.Position{X: 700, Y: 100},
				Metadata: map[string]string{
					"step_number": "4",
					"category":   "service",
					"bootstrap_id": "logging:init-provider",
				},
			},
			{
				ID:        "components:init-container",
				Name:      "初始化组件容器",
				Type:      StartupNodeService,
				Description: "初始化组件容器，管理所有依赖注入",
				DependsOn: []string{"logging:init-provider"},
				Config: map[string]interface{}{
					"enable_di_container": false,
					"enable_runtime_container": false,
				},
				Status:    workflow.NodeStatusPending,
				Timeout:   30 * time.Second,
				Critical:  false,
				Position: workflow.Position{X: 900, Y: 100},
				Metadata: map[string]string{
					"step_number": "5",
					"category":   "service",
					"bootstrap_id": "components:init-container",
				},
			},
			{
				ID:        "config:init-integrator",
				Name:      "初始化配置集成器",
				Type:      StartupNodeService,
				Description: "初始化配置集成器，统一配置管理",
				DependsOn: []string{"components:init-container", "logging:init-provider"},
				Config: map[string]interface{}{
					"enable_env_config": true,
					"enable_file_config": true,
					"config_watch_interval": "30s",
				},
				Status:    workflow.NodeStatusPending,
				Timeout:   30 * time.Second,
				Critical: false,
				Position: workflow.Position{X: 1100, Y: 100},
				Metadata: map[string]string{
					"step_number": "6",
					"category":   "service",
					"bootstrap_id": "config:init-integrator",
				},
			},
			{
				ID:        "auth:init-manager",
				Name:      "初始化认证管理器",
				Type:      StartupNodeAuth,
				Description: "初始化认证管理器，设置用户认证和会话管理",
				DependsOn: []string{"components:init-container"},
				Config: map[string]interface{}{
					"auth_store": "database",
					"session_ttl": "24h",
					"cleanup_interval": "10m",
					"enable_oauth": false,
					"enable_jwt": true,
					"jwt_secret": "your-jwt-secret-key",
				},
				Status:    workflow.NodeStatusPending,
				Timeout:   60 * time.Second,
				Critical:  true,
				Position: workflow.Position{X: 1300, Y: 100},
				Metadata: map[string]string{
					"step_number": "7",
					"category":   "auth",
					"bootstrap_id": "auth:init-manager",
				},
			},
			{
				ID:        "mcp:init-manager",
				Name:      "初始化MCP管理器",
				Type:      StartupNodeService,
				Description: "初始化MCP（Model Context Protocol）管理器",
				DependsOn: []string{"logging:init-provider"},
				Config: map[string]interface{}{
					"enable_global_manager": true,
					"enable_local_clients": true,
					"tool_timeout": "30s",
					"max_retries": 3,
				},
				Status:    workflow.NodeStatusPending,
				Timeout:   45 * time.Second,
				Critical: false,
				Optional:  true,
				Position: workflow.Position{X: 1500, Y: 100},
				Metadata: map[string]string{
					"step_number": "8",
					"category":   "service",
					"bootstrap_id": "mcp:init-manager",
				},
			},
			{
				ID:        "observability:setup-hooks",
				Name:      "设置可观测性钩子",
				Type:      StartupNodeService,
				Description: "设置可观测性钩子，包括指标收集和分布式追踪",
				DependsOn: []string{"logging:init-provider"},
				Config: map[string]interface{}{
					"enable_metrics": true,
					"enable_tracing": false,
					"metrics_endpoint": "/metrics",
					"tracing_endpoint": "",
				},
				Status:    workflow.NodeStatusPending,
				Timeout:   30 * time.Second,
				Critical: false,
				Optional:  true,
				Position: workflow.Position{X: 1700, Y: 100},
				Metadata: map[string]string{
					"step_number": "9",
					"category":   "service",
					"bootstrap_id": "observability:setup-hooks",
				},
			},
			{
				ID:        "plugin:init-manager",
				Name:      "初始化插件管理器",
				Type:      StartupNodePlugin,
				Description: "初始化插件管理器，设置插件发现和管理功能",
				DependsOn: []string{"logging:init-provider"},
				Config: map[string]interface{}{
					"enable_discovery": true,
					"discovery_paths": []string{"./plugins", "./plugins/examples"},
					"scan_interval": "30s",
					"health_check_interval": "10s",
					"enable_health_check": true,
					"registry_type": "memory",
					"registry_ttl": "5m",
				},
				Status:    workflow.NodeStatusPending,
				Timeout:   60 * time.Second,
				Critical:  false,
				Optional:  true,
				Position: workflow.Position{X: 1900, Y: 100},
				Metadata: map[string]string{
					"step_number": "10",
					"category":   "plugin",
					"bootstrap_id": "plugin:init-manager",
				},
			},
			{
				ID:        "start-services",
				Name:      "启动系统服务",
				Type:      StartupNodeService,
				Description: "启动HTTP、WebSocket、OTA等系统服务",
				DependsOn: []string{
					"storage:init-database",
					"config:load-default",
					"auth:init-manager",
				},
				Config: map[string]interface{}{
					"start_http_server": true,
					"start_websocket_server": true,
					"start_ota_service": true,
					"http_port": 8080,
					"websocket_port": 8001,
					"enable_static_serving": true,
					"enable_api_docs": true,
				},
				Status:    workflow.NodeStatusPending,
				Timeout:   90 * time.Second,
				Critical:  true,
				Position: workflow.Position{X: 2100, Y: 100},
				Metadata: map[string]string{
					"step_number": "11",
					"category":   "service",
					"bootstrap_id": "start-services",
				},
			},
		},
		Edges: []workflow.Edge{
			{ID: "e1", From: "storage:init-config-store", To: "storage:init-database", Label: "依赖"},
			{ID: "e2", From: "storage:init-database", To: "config:load-default", Label: "依赖"},
			{ID: "e3", From: "config:load-default", To: "logging:init-provider", Label: "依赖"},
			{ID: "e4", From: "logging:init-provider", To: "components:init-container", Label: "依赖"},
			{ID: "e5", From: "components:init-container", To: "config:init-integrator", Label: "依赖"},
			{ID: "e6", From: "components:init-container", To: "auth:init-manager", Label: "依赖"},
			{ID: "e7", From: "logging:init-provider", To: "mcp:init-manager", Label: "依赖"},
			{ID: "e8", From: "logging:init-provider", To: "observability:setup-hooks", Label: "依赖"},
			{ID: "e9", From: "logging:init-provider", To: "plugin:init-manager", Label: "依赖"},
			{ID: "e10", From: "config:load-default", To: "start-services", Label: "依赖"},
			{ID: "e11", From: "auth:init-manager", To: "start-services", Label: "依赖"},
		},
	}
}

// CreateParallelStartupWorkflow 创建并行启动工作流（优化版本）
func CreateParallelStartupWorkflow() *StartupWorkflow {
	return &StartupWorkflow{
		ID:          "xiaozhi-flow-parallel-startup",
		Name:        "XiaoZhi Flow 并行启动工作流",
		Description: "优化的并行启动工作流，支持并行执行无依赖的步骤",
		Version:     "1.0.0",
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		Tags:        []string{"parallel", "optimized", "system", "startup"},
		Config: StartupWorkflowConfig{
			Timeout:       DefaultTimeout,
			MaxRetries:    DefaultMaxRetries,
			ParallelLimit: 8, // 提高并行度
			EnableLog:     true,
			Environment:   make(map[string]interface{}),
			Variables:     make(map[string]interface{}),
			OnFailure:     FailureActionStop,
		},
		Nodes: []StartupNode{
			// 层次1：存储层（顺序执行）
			{
				ID:        "storage:init-config-store",
				Name:      "初始化配置存储",
				Type:      StartupNodeStorage,
				Description: "初始化配置存储系统",
				DependsOn: []string{},
				Config: map[string]interface{}{
					"storage_type": "file",
					"config_path": "config/",
				},
				Status:    workflow.NodeStatusPending,
				Timeout:   30 * time.Second,
				Critical:  true,
				Position: workflow.Position{X: 100, Y: 50},
			},
			{
				ID:        "storage:init-database",
				Name:      "初始化数据库",
				Type:      StartupNodeStorage,
				Description: "初始化数据库连接",
				DependsOn: []string{"storage:init-config-store"},
				Config: map[string]interface{}{
					"database_type": "sqlite",
					"connection_string": "./data/xiaozhi.db",
					"auto_migrate": true,
					"w_mode":      true,
				},
				Status:    workflow.NodeStatusPending,
				Timeout:   60 * time.Second,
				Critical:  true,
				Position: workflow.Position{X: 300, Y: 50},
			},

			// 层次2：配置层（基于存储层）
			{
				ID:        "config:load-default",
				Name:      "加载默认配置",
				Type:      StartupNodeConfig,
				Description: "从数据库加载默认配置",
				DependsOn: []string{"storage:init-config-store", "storage:init-database"},
				Config: map[string]interface{}{
					"config_file": "default_config.json",
					"fallback_to_defaults": true,
				},
				Status:    workflow.NodeStatusPending,
				Timeout:   30 * time.Second,
				Critical:  true,
				Position: workflow.Position{X: 500, Y: 50},
			},

			// 层次3：服务层（基于配置层，可并行执行）
			{
				ID:        "logging:init-provider",
				Name:      "初始化日志系统",
				Type:      StartupNodeService,
				Description: "初始化日志提供者",
				DependsOn: []string{"config:load-default"},
				Config: map[string]interface{}{
					"log_level": "info",
					"log_dir":   "logs/",
					"log_file":  "xiaozhi-server.log",
				},
				Status:    workflow.NodeStatusPending,
				Timeout:   20 * time.Second,
				Position: workflow.Position{X: 700, Y: 100},
			},
			{
				ID:        "components:init-container",
				Name:      "初始化组件容器",
				Type:      StartupNodeService,
				Description: "初始化组件容器",
				DependsOn: []string{"logging:init-provider"},
				Config: map[string]interface{}{
					"enable_di_container": false,
					"enable_runtime_container": false,
				},
				Status:    workflow.NodeStatusPending,
				Timeout:   30 * time.Second,
				Position: workflow.Position{X: 900, Y: 100},
			},
			{
				ID:        "config:init-integrator",
				Name:      "初始化配置集成器",
				Type:      StartupNodeService,
				Description: "初始化配置集成器",
				DependsOn: []string{"components:init-container", "logging:init-provider"},
				Config: map[string]interface{}{
					"enable_env_config": true,
					"enable_file_config": true,
				},
				Status:    workflow.NodeStatusPending,
				Timeout:   30 * time.Second,
				Position: workflow.Position{X: 1100, Y: 100},
			},
			{
				ID:        "auth:init-manager",
				Name:      "初始化认证管理器",
				Type:      StartupNodeAuth,
				Description: "初始化认证管理器",
				DependsOn: []string{"components:init-container"},
				Config: map[string]interface{}{
					"auth_store": "database",
					"session_ttl": "24h",
				},
				Status:    workflow.NodeStatusPending,
				Timeout:   60 * time.Second,
				Critical:  true,
				Position: workflow.Position{X: 1300, Y: 100},
			},

			// 层次4：扩展服务（可并行执行）
			{
				ID:        "mcp:init-manager",
				Name:      "初始化MCP管理器",
				Type:      StartupNodeService,
				Description: "初始化MCP管理器",
				DependsOn: []string{"logging:init-provider"},
				Config: map[string]interface{}{
					"enable_global_manager": true,
					"enable_local_clients": true,
				},
				Status:    workflow.NodeStatusPending,
				Timeout:   45 * time.Second,
				Optional:  true,
				Position: workflow.Position{X: 1500, Y: 200},
			},
			{
				ID:        "observability:setup-hooks",
				Name:      "设置可观测性钩子",
				Type:      StartupNodeService,
				Description: "设置可观测性钩子",
				DependsOn: []string{"logging:init-provider"},
				Config: map[string]interface{}{
					"enable_metrics": true,
				},
				Status:    workflow.NodeStatusPending,
				Timeout:   30 * time.Second,
				Optional:  true,
				Position: workflow.Position{X: 1700, Y: 200},
			},
			{
				ID:        "plugin:init-manager",
				Name:      "初始化插件管理器",
				Type:      StartupNodePlugin,
				Description: "初始化插件管理器",
				DependsOn: []string{"logging:init-provider"},
				Config: map[string]interface{}{
					"enable_discovery": true,
					"discovery_paths": []string{"./plugins", "./plugins/examples"},
					"scan_interval": "30s",
				},
				Status:    workflow.NodeStatusPending,
				Timeout:   60 * time.Second,
				Optional:  true,
				Position: workflow.Position{X: 1900, Y: 200},
			},

			// 层次5：服务启动（基于多个依赖）
			{
				ID:        "start-services",
				Name:      "启动系统服务",
				Type:      StartupNodeService,
				Description: "启动HTTP、WebSocket、OTA等系统服务",
				DependsOn: []string{
					"storage:init-database",
					"config:load-default",
					"logging:init-provider",
					"components:init-container",
					"config:init-integrator",
					"auth:init-manager",
				},
				Config: map[string]interface{}{
					"start_http_server": true,
					"start_websocket_server": true,
					"start_ota_service": true,
					"http_port": 8080,
					"websocket_port": 8001,
					"enable_static_serving": true,
					"enable_api_docs": true,
				},
				Status:    workflow.NodeStatusPending,
				Timeout:   120 * time.Second,
				Critical:  true,
				Position: workflow.Position{X: 2100, Y: 100},
			},
		},
		Edges: []workflow.Edge{
			// 层次1依赖
			{ID: "e1", From: "storage:init-config-store", To: "storage:init-database"},
			{ID: "e2", From: "storage:init-database", To: "config:load-default"},

			// 层次2依赖
			{ID: "e3", From: "storage:init-config-store", To: "config:load-default"},
			{ID: "e4", From: "storage:init-database", To: "config:load-default"},

			// 层次3依赖
			{ID: "e5", From: "config:load-default", To: "logging:init-provider"},
			{ID: "e6", From: "logging:init-provider", To: "components:init-container"},
			{ID: "e7", From: "logging:init-provider", To: "config:init-integrator"},
			{ID: "e8", From: "logging:init-provider", To: "auth:init-manager"},

			// 层次4依赖
			{ID: "e9", From: "components:init-container", To: "config:init-integrator"},

			// 层次5依赖
			{ID: "e10", From: "config:load-default", To: "start-services"},
			{ID: "e11", From: "auth:init-manager", To: "start-services"},
			{ID: "e12", From: "logging:init-provider", To: "start-services"},
			{ID: "e13", From: "components:init-container", To: "start-services"},
			{ID: "e14", From: "config:init-integrator", To: "start-services"},

			// 扩展服务依赖（可选）
			{ID: "e15", From: "logging:init-provider", To: "mcp:init-manager"},
			{ID: "e16", From: "logging:init-provider", To: "observability:setup-hooks"},
			{ID: "e17", From: "logging:init-provider", To: "plugin:init-manager"},
		},
	}
}

// CreateMinimalStartupWorkflow 创建最小启动工作流
func CreateMinimalStartupWorkflow() *StartupWorkflow {
	return &StartupWorkflow{
		ID:          "xiaozhi-flow-minimal-startup",
		Name:        "XiaoZhi Flow 最小启动工作流",
		Description: "仅包含必要组件的最小化启动工作流",
		Version:     "1.0.0",
		CreatedAt:   time.Now(),
		UpdatedAt:   time.Now(),
		Config: StartupWorkflowConfig{
			Timeout:       5 * time.Minute,
			MaxRetries:    1,
			ParallelLimit: 2,
			EnableLog:     true,
			Environment:   make(map[string]interface{}),
			Variables:     make(map[string]interface{}),
			OnFailure:     FailureActionStop,
		},
		Nodes: []StartupNode{
			{
				ID:        "storage:init-database",
				Name:      "初始化数据库",
				Type:      StartupNodeStorage,
				Description: "初始化SQLite数据库",
				DependsOn: []string{},
				Config: map[string]interface{}{
					"database_type": "sqlite",
					"connection_string": "./data/xiaozhi.db",
					"auto_migrate": true,
					"w_mode":      true,
				},
				Status:    workflow.NodeStatusPending,
				Timeout:   30 * time.Second,
				Critical:  true,
				Position: workflow.Position{X: 200, Y: 100},
			},
			{
				ID:        "config:load-default",
				Name:      "加载默认配置",
				Type:      StartupNodeConfig,
				Description: "加载内置默认配置",
				DependsOn: []string{"storage:init-database"},
				Config: map[string]interface{}{
					"use_builtin_defaults": true,
				},
				Status:    workflow.NodeStatusPending,
				Timeout:   10 * time.Second,
				Critical:  true,
				Position: workflow.Position{X: 400, Y: 100},
			},
			{
				ID:        "logging:init-provider",
				Name:      "初始化日志系统",
				Type:      StartupNodeService,
				Description: "初始化基本日志功能",
				DependsOn: []string{"config:load-default"},
				Config: map[string]interface{}{
					"log_level": "info",
					"console": true,
					"file": false,
				},
				Status:    workflow.NodeStatusPending,
				Timeout:   15 * time.Second,
				Critical:  false,
				Position: workflow.Position{X: 600, Y: 100},
			},
			{
				ID:        "start-basic-services",
				Name:      "启动基础服务",
				Type:      StartupNodeService,
				Description: "启动HTTP和WebSocket基础服务",
				DependsOn: []string{"storage:init-database", "logging:init-provider"},
				Config: map[string]interface{}{
					"http_port": 8080,
					"websocket_port": 8001,
					"enable_static_serving": true,
				},
				Status:    workflow.NodeStatusPending,
				Timeout:   60 * time.Second,
				Critical:  true,
				Position: workflow.Position{X: 800, Y: 100},
			},
		},
		Edges: []workflow.Edge{
			{ID: "e1", From: "storage:init-database", To: "config:load-default"},
			{ID: "e2", From: "config:load-default", To: "logging:init-provider"},
			{ID: "e3", From: "storage:init-database", To: "start-basic-services"},
			{ID: "e4", From: "logging:init-provider", To: "start-basic-services"},
		},
	}
}