// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.0
// 	protoc        v4.25.3
// source: api/v1/plugin.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamp"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 插件类型枚举
type PluginType int32

const (
	PluginType_PLUGIN_TYPE_UNSPECIFIED PluginType = 0
	PluginType_PLUGIN_TYPE_AUDIO       PluginType = 1
	PluginType_PLUGIN_TYPE_LLM         PluginType = 2
	PluginType_PLUGIN_TYPE_DEVICE      PluginType = 3
	PluginType_PLUGIN_TYPE_UTILITY     PluginType = 4
	PluginType_PLUGIN_TYPE_CUSTOM      PluginType = 5
)

// Enum value maps for PluginType.
var (
	PluginType_name = map[int32]string{
		0: "PLUGIN_TYPE_UNSPECIFIED",
		1: "PLUGIN_TYPE_AUDIO",
		2: "PLUGIN_TYPE_LLM",
		3: "PLUGIN_TYPE_DEVICE",
		4: "PLUGIN_TYPE_UTILITY",
		5: "PLUGIN_TYPE_CUSTOM",
	}
	PluginType_value = map[string]int32{
		"PLUGIN_TYPE_UNSPECIFIED": 0,
		"PLUGIN_TYPE_AUDIO":       1,
		"PLUGIN_TYPE_LLM":         2,
		"PLUGIN_TYPE_DEVICE":      3,
		"PLUGIN_TYPE_UTILITY":     4,
		"PLUGIN_TYPE_CUSTOM":      5,
	}
)

func (x PluginType) Enum() *PluginType {
	p := new(PluginType)
	*p = x
	return p
}

func (x PluginType) String() string {
	return PluginType_name[int32(x)]
}

func (PluginType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (PluginType) Type() protoreflect.EnumType {
	return &file_api_v1_plugin_proto_enumTypes[0]
}

func (x PluginType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// 插件状态枚举
type PluginStatus int32

const (
	PluginStatus_PLUGIN_STATUS_UNSPECIFIED PluginStatus = 0
	PluginStatus_PLUGIN_STATUS_STOPPED     PluginStatus = 1
	PluginStatus_PLUGIN_STATUS_STARTING    PluginStatus = 2
	PluginStatus_PLUGIN_STATUS_RUNNING     PluginStatus = 3
	PluginStatus_PLUGIN_STATUS_STOPPING    PluginStatus = 4
	PluginStatus_PLUGIN_STATUS_ERROR       PluginStatus = 5
)

// Enum value maps for PluginStatus.
var (
	PluginStatus_name = map[int32]string{
		0: "PLUGIN_STATUS_UNSPECIFIED",
		1: "PLUGIN_STATUS_STOPPED",
		2: "PLUGIN_STATUS_STARTING",
		3: "PLUGIN_STATUS_RUNNING",
		4: "PLUGIN_STATUS_STOPPING",
		5: "PLUGIN_STATUS_ERROR",
	}
	PluginStatus_value = map[string]int32{
		"PLUGIN_STATUS_UNSPECIFIED": 0,
		"PLUGIN_STATUS_STOPPED":     1,
		"PLUGIN_STATUS_STARTING":    2,
		"PLUGIN_STATUS_RUNNING":     3,
		"PLUGIN_STATUS_STOPPING":    4,
		"PLUGIN_STATUS_ERROR":       5,
	}
)

func (x PluginStatus) Enum() *PluginStatus {
	p := new(PluginStatus)
	*p = x
	return p
}

func (x PluginStatus) String() string {
	return PluginStatus_name[int32(x)]
}

func (PluginStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_plugin_proto_enumTypes[1].Descriptor()
}

func (PluginStatus) Type() protoreflect.EnumType {
	return &file_api_v1_plugin_proto_enumTypes[1]
}

func (x PluginStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// 插件信息
type PluginInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                  // 插件唯一标识
	Name        string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                            // 插件名称
	Version     string               `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                      // 插件版本
	Description string               `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`              // 插件描述
	Author      string               `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`                        // 插件作者
	Tags        []string             `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`                            // 插件标签
	Type        PluginType           `protobuf:"varint,7,opt,name=type,proto3,enum=plugin.v1.PluginType" json:"type,omitempty"` // 插件类型
	Capabilities []string            `protobuf:"bytes,8,rep,name=capabilities,proto3" json:"capabilities,omitempty"`            // 插件能力
	Metadata    *structpb.Struct     `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`                   // 插件元数据
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_plugin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_plugin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_api_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *PluginInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PluginInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PluginInfo) GetType() PluginType {
	if x != nil {
		return x.Type
	}
	return PluginType_PLUGIN_TYPE_UNSPECIFIED
}

func (x *PluginInfo) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *PluginInfo) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// 错误信息
type ErrorInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string            `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                // 错误码
	Message string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`          // 错误消息
	Details string            `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`          // 错误详情
	Context map[string]string `protobuf:"bytes,4,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 错误上下文
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_plugin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_plugin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_api_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorInfo) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *ErrorInfo) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

// 执行结果
type ExecutionResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success  bool               `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                          // 执行是否成功
	Message  string             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                        // 结果消息
	Data     *structpb.Struct   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                              // 结果数据
	Error    *ErrorInfo         `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                            // 错误信息
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`               // 执行时间戳
}

func (x *ExecutionResult) Reset() {
	*x = ExecutionResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_plugin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecutionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionResult) ProtoMessage() {}

func (x *ExecutionResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_plugin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionResult.ProtoReflect.Descriptor instead.
func (*ExecutionResult) Descriptor() ([]byte, []int) {
	return file_api_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutionResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecutionResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecutionResult) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExecutionResult) GetError() *ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ExecutionResult) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_api_v1_plugin_proto protoreflect.FileDescriptor

var file_api_v1_plugin_proto_rawDesc = []byte{
	// 548 bytes of a gzipped FileDescriptorProto
}

var (
	file_api_v1_plugin_proto_rawDescOnce sync.Once
	file_api_v1_plugin_proto_rawDescData = file_api_v1_plugin_proto_rawDesc
)

func file_api_v1_plugin_proto_rawDescGZIP() []byte {
	file_api_v1_plugin_proto_rawDescOnce.Do(func() {
		file_api_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_plugin_proto_rawDescData)
	})
	return file_api_v1_plugin_proto_rawDescData
}

var file_api_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_v1_plugin_proto_goTypes = []interface{}{
	(PluginType)(0),        // 0: plugin.v1.PluginType
	(PluginStatus)(0),      // 1: plugin.v1.PluginStatus
	(*PluginInfo)(nil),     // 2: plugin.v1.PluginInfo
	(*ErrorInfo)(nil),      // 3: plugin.v1.ErrorInfo
	(*ExecutionResult)(nil), // 4: plugin.v1.ExecutionResult
	(*structpb.Struct)(nil), // 5: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_api_v1_plugin_proto_depIdxs = []int32{
	5, // [5:5] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_v1_plugin_proto_init() }
func file_api_v1_plugin_proto_init() {
	if File_api_v1_plugin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_plugin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_plugin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_plugin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecutionResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_v1_plugin_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_api_v1_plugin_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_api_v1_plugin_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_plugin_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_plugin_proto_goTypes,
		DependencyIndexes: file_api_v1_plugin_proto_depIdxs,
		EnumInfos:         file_api_v1_plugin_proto_enumTypes,
		MessageInfos:      file_api_v1_plugin_proto_msgTypes,
	}.Build()
	File_api_v1_plugin_proto = out.File
	file_api_v1_plugin_proto_rawDesc = nil
	file_api_v1_plugin_proto_goTypes = nil
	file_api_v1_plugin_proto_depIdxs = nil
}