// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/config/records": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取所有配置记录，支持分页和过滤",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "获取配置记录列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "按分类过滤",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "按活跃状态过滤",
                        "name": "active",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/webapi.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/webapi.ConfigRecordResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "创建新的配置记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "创建配置记录",
                "parameters": [
                    {
                        "description": "配置记录数据",
                        "name": "record",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webapi.CreateConfigRecordRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/webapi.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/webapi.ConfigRecord"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/admin/config/records/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据ID获取配置记录详情",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "获取单个配置记录",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "配置记录ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/webapi.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/webapi.ConfigRecord"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据ID更新配置记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "更新配置记录",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "配置记录ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "配置记录更新数据",
                        "name": "record",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webapi.UpdateConfigRecordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/webapi.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/webapi.ConfigRecord"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据ID删除配置记录",
                "tags": [
                    "Admin"
                ],
                "summary": "删除配置记录",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "配置记录ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webapi.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/admin/database/schema": {
            "get": {
                "description": "获取数据库的完整模式信息，包括表、列、索引等",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "获取数据库模式",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webapi.DatabaseSchema"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/admin/database/tables": {
            "get": {
                "description": "获取数据库中所有表的基本信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "获取数据库表列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/admin/system": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取服务器的系统配置信息，包括选择的提供商和默认提示词",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "获取系统配置",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webapi.SystemConfig"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/admin/system/database-config": {
            "get": {
                "description": "获取当前保存的数据库配置（不包含密码）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "获取数据库配置",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/admin/system/init": {
            "post": {
                "description": "初始化Xiaozhi-Flow系统，创建数据库和管理员用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "系统初始化",
                "parameters": [
                    {
                        "description": "初始化配置",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webapi.InitRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/admin/system/save-database-config": {
            "post": {
                "description": "保存数据库配置到配置文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "保存数据库配置",
                "parameters": [
                    {
                        "description": "数据库配置",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webapi.DatabaseConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/admin/system/status": {
            "get": {
                "description": "获取当前系统的运行状态和服务信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "获取系统状态",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/admin/system/test-connection": {
            "post": {
                "description": "测试与指定数据库的连接状态和延迟",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "测试数据库连接",
                "parameters": [
                    {
                        "description": "数据库配置",
                        "name": "config",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webapi.DatabaseConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webapi.ConnectionTestResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/admin/system/test-database-step": {
            "post": {
                "description": "分步骤测试数据库配置和连接",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "测试数据库配置步骤",
                "parameters": [
                    {
                        "description": "步骤信息",
                        "name": "step",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webapi.DatabaseTestStepRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Authenticate user with username and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webapi.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webapi.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Logout the current user and invalidate the session",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "User logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/auth/logout-all": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Logout the user from all active sessions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout from all devices",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get information about the currently authenticated user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webapi.UserInfo"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Refresh the authentication token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webapi.AuthResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Register a new user account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "User registration",
                "parameters": [
                    {
                        "description": "Registration information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webapi.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/webapi.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/cfg": {
            "get": {
                "description": "检查配置服务的运行状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Config"
                ],
                "summary": "检查配置服务状态",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/ota/": {
            "post": {
                "description": "处理设备OTA请求，包括设备注册、激活码生成和固件信息返回",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OTA"
                ],
                "summary": "OTA设备注册和固件更新",
                "parameters": [
                    {
                        "type": "string",
                        "description": "设备ID",
                        "name": "device-id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "客户端ID",
                        "name": "client-id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "设备信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ota.OTAResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/vision": {
            "get": {
                "description": "获取Vision服务的运行状态和可用模型信息",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Vision"
                ],
                "summary": "检查Vision服务状态",
                "responses": {
                    "200": {
                        "description": "服务状态信息",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "上传图片并进行视觉分析，支持问题询问",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Vision"
                ],
                "summary": "图片视觉分析",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "设备ID",
                        "name": "Device-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "客户端ID",
                        "name": "Client-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "图片文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "分析问题",
                        "name": "question",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vision.VisionAnalysisData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ota.Activation": {
            "type": "object",
            "properties": {
                "challenge": {
                    "description": "用于设备认证挑战",
                    "type": "string"
                },
                "code": {
                    "type": "string",
                    "example": "543091"
                },
                "message": {
                    "type": "string",
                    "example": "Anime AI Chat 543091"
                }
            }
        },
        "ota.FirmwareInfo": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string",
                    "example": "/ota_bin/1.2.4.bin"
                },
                "version": {
                    "type": "string",
                    "example": "1.2.4"
                }
            }
        },
        "ota.MQTTInfo": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string",
                    "example": "CGID_test@@@mac@@@client"
                },
                "endpoint": {
                    "type": "string",
                    "example": "mqtt://broker:1883"
                },
                "password": {
                    "type": "string",
                    "example": "randomPwd"
                },
                "publish_topic": {
                    "type": "string",
                    "example": "device-server"
                },
                "subscribe_topic": {
                    "type": "string",
                    "example": "null"
                },
                "username": {
                    "type": "string",
                    "example": "base64string"
                }
            }
        },
        "ota.OTAResponse": {
            "type": "object",
            "properties": {
                "activation": {
                    "$ref": "#/definitions/ota.Activation"
                },
                "firmware": {
                    "$ref": "#/definitions/ota.FirmwareInfo"
                },
                "mqtt": {
                    "$ref": "#/definitions/ota.MQTTInfo"
                },
                "server_time": {
                    "$ref": "#/definitions/ota.ServerTimeInfo"
                },
                "websocket": {
                    "$ref": "#/definitions/ota.WebSocketInfo"
                }
            }
        },
        "ota.ServerTimeInfo": {
            "type": "object",
            "properties": {
                "timestamp": {
                    "type": "integer",
                    "example": 1720065289451
                },
                "timezone_offset": {
                    "type": "integer",
                    "example": 480
                }
            }
        },
        "ota.WebSocketInfo": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string",
                    "example": "wss://your-server/ws"
                }
            }
        },
        "vision.VisionAnalysisData": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "错误信息（失败时）",
                    "type": "string"
                },
                "result": {
                    "description": "分析结果（成功时）",
                    "type": "string"
                }
            }
        },
        "webapi.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "webapi.AdminConfig": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "type": {
                    "description": "\"random\" 或 \"custom\"",
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "webapi.AuthResponse": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "integer"
                },
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/webapi.UserInfo"
                }
            }
        },
        "webapi.ColumnInfo": {
            "type": "object",
            "properties": {
                "defaultValue": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "nullable": {
                    "type": "boolean"
                },
                "primaryKey": {
                    "type": "boolean"
                },
                "type": {
                    "type": "string"
                },
                "unique": {
                    "type": "boolean"
                }
            }
        },
        "webapi.ConfigRecord": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "key": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "value": {},
                "version": {
                    "type": "integer"
                }
            }
        },
        "webapi.ConfigRecordResponse": {
            "type": "object",
            "properties": {
                "pagination": {
                    "$ref": "#/definitions/webapi.Pagination"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/webapi.ConfigRecord"
                    }
                }
            }
        },
        "webapi.ConnectionTestResult": {
            "type": "object",
            "properties": {
                "latency": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "services": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "boolean"
                    }
                },
                "success": {
                    "type": "boolean"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "webapi.CreateConfigRecordRequest": {
            "type": "object",
            "required": [
                "key",
                "value"
            ],
            "properties": {
                "category": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "key": {
                    "type": "string"
                },
                "value": {}
            }
        },
        "webapi.DatabaseConfig": {
            "type": "object",
            "properties": {
                "database": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "path": {
                    "description": "SQLite数据库文件路径",
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "webapi.DatabaseSchema": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "relationships": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/webapi.ForeignKeyInfo"
                    }
                },
                "tables": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/webapi.TableInfo"
                    }
                },
                "totalRows": {
                    "type": "integer"
                },
                "totalTables": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "webapi.DatabaseTestStepRequest": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/webapi.DatabaseConfig"
                },
                "step": {
                    "type": "integer"
                }
            }
        },
        "webapi.ForeignKeyInfo": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "onDelete": {
                    "type": "string"
                },
                "onUpdate": {
                    "type": "string"
                },
                "sourceColumn": {
                    "type": "string"
                },
                "sourceTable": {
                    "type": "string"
                },
                "targetColumn": {
                    "type": "string"
                },
                "targetTable": {
                    "type": "string"
                }
            }
        },
        "webapi.IndexInfo": {
            "type": "object",
            "properties": {
                "columns": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "unique": {
                    "type": "boolean"
                }
            }
        },
        "webapi.InitRequest": {
            "type": "object",
            "properties": {
                "adminConfig": {
                    "$ref": "#/definitions/webapi.AdminConfig"
                },
                "databaseConfig": {
                    "$ref": "#/definitions/webapi.DatabaseConfig"
                },
                "providers": {
                    "type": "object",
                    "additionalProperties": true
                },
                "systemConfig": {}
            }
        },
        "webapi.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "webapi.Pagination": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "pages": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "webapi.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "webapi.SystemConfig": {
            "type": "object",
            "properties": {
                "prompt": {
                    "type": "string"
                },
                "selectedASR": {
                    "type": "string"
                },
                "selectedLLM": {
                    "type": "string"
                },
                "selectedTTS": {
                    "type": "string"
                },
                "selectedVLLLM": {
                    "type": "string"
                }
            }
        },
        "webapi.TableInfo": {
            "type": "object",
            "properties": {
                "columns": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/webapi.ColumnInfo"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "indexes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/webapi.IndexInfo"
                    }
                },
                "name": {
                    "type": "string"
                },
                "rowCount": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "webapi.UpdateConfigRecordRequest": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "value": {}
            }
        },
        "webapi.UserInfo": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "小智服务端 API 文档",
	Description:      "小智服务端，包含OTA与Vision等接口",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
