// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cfg": {
            "get": {
                "description": "检查配置服务的运行状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Config"
                ],
                "summary": "检查配置服务状态",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/ota/": {
            "post": {
                "description": "处理设备OTA请求，包括设备注册、激活码生成和固件信息返回",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OTA"
                ],
                "summary": "OTA设备注册和固件更新",
                "parameters": [
                    {
                        "type": "string",
                        "description": "设备ID",
                        "name": "device-id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "客户端ID",
                        "name": "client-id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "设备信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ota.OTAResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/system": {
            "get": {
                "description": "获取系统状态信息，根据用户权限返回不同级别的信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "获取系统信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httptransport.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.UnifiedSystemInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "执行系统健康检查、重启等操作",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "执行系统操作",
                "parameters": [
                    {
                        "description": "系统操作请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.SystemOperationRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httptransport.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {}
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/devices": {
            "get": {
                "description": "获取设备列表，支持分页和过滤",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Devices"
                ],
                "summary": "获取设备列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "按状态过滤",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "按设备类型过滤",
                        "name": "device_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "搜索关键词",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "created_at",
                        "description": "排序字段",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "desc",
                        "description": "排序方向",
                        "name": "sort_order",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "是否返回位置信息",
                        "name": "location",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httptransport.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.DeviceListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "新设备注册到系统",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Devices"
                ],
                "summary": "设备注册",
                "parameters": [
                    {
                        "description": "设备注册信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.DeviceRegistrationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httptransport.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.DeviceInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httptransport.APIResponse"
                        }
                    }
                }
            }
        },
        "/v1/devices/status": {
            "post": {
                "description": "管理员快速激活或禁用设备，通过设备MAC地址和激活状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Devices"
                ],
                "summary": "管理员激活/禁用设备",
                "parameters": [
                    {
                        "description": "设备状态管理请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.DeviceStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httptransport.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.DeviceStatusResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httptransport.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httptransport.APIResponse"
                        }
                    }
                }
            }
        },
        "/v1/devices/{id}": {
            "get": {
                "description": "根据ID获取设备的详细信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Devices"
                ],
                "summary": "获取设备详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "设备ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httptransport.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.DeviceInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httptransport.APIResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "更新指定设备的信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Devices"
                ],
                "summary": "更新设备信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "设备ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "设备更新信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.DeviceUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httptransport.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.DeviceInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httptransport.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httptransport.APIResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "从系统中删除指定设备",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Devices"
                ],
                "summary": "删除设备",
                "parameters": [
                    {
                        "type": "string",
                        "description": "设备ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httptransport.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httptransport.APIResponse"
                        }
                    }
                }
            }
        },
        "/v1/devices/{id}/activate": {
            "post": {
                "description": "激活已注册的设备",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Devices"
                ],
                "summary": "激活设备",
                "parameters": [
                    {
                        "type": "string",
                        "description": "设备ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "设备激活信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.DeviceActivationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httptransport.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.DeviceActivationResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httptransport.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httptransport.APIResponse"
                        }
                    }
                }
            }
        },
        "/v1/providers": {
            "get": {
                "description": "获取所有配置的AI服务供应商",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Providers"
                ],
                "summary": "获取供应商列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httptransport.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.ProviderList"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "创建新的AI服务供应商配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Providers"
                ],
                "summary": "创建供应商配置",
                "parameters": [
                    {
                        "description": "供应商配置",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.ProviderConfigRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httptransport.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.Provider"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httptransport.APIResponse"
                        }
                    }
                }
            }
        },
        "/v1/providers/{type}/{name}": {
            "put": {
                "description": "更新指定供应商的配置信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Providers"
                ],
                "summary": "更新供应商配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "供应商类型",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "供应商名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "供应商配置",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.ProviderConfigRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httptransport.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.Provider"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httptransport.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httptransport.APIResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除指定的供应商配置",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Providers"
                ],
                "summary": "删除供应商配置",
                "parameters": [
                    {
                        "type": "string",
                        "description": "供应商类型",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "供应商名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httptransport.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httptransport.APIResponse"
                        }
                    }
                }
            }
        },
        "/v1/system/config": {
            "get": {
                "description": "获取系统配置项列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "获取系统配置",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httptransport.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/v1.SystemConfigResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "更新指定的系统配置项",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "更新系统配置",
                "parameters": [
                    {
                        "description": "配置更新信息",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.SystemConfigRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httptransport.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.SystemConfigResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httptransport.APIResponse"
                        }
                    }
                }
            }
        },
        "/v1/system/health": {
            "get": {
                "description": "快速健康检查",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httptransport.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.HealthCheckResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "执行详细的健康检查，支持指定检查项目",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "详细健康检查",
                "parameters": [
                    {
                        "description": "健康检查参数",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/v1.HealthCheckRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httptransport.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.HealthCheckResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/system/status": {
            "get": {
                "description": "获取系统的运行状态和统计信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "获取系统状态",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httptransport.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.SystemStatus"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/system/time": {
            "get": {
                "description": "获取服务器当前时间和相关信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "获取服务器时间",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/httptransport.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/v1.ServerTimeInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/vision": {
            "get": {
                "description": "获取Vision服务的运行状态和可用模型信息",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Vision"
                ],
                "summary": "检查Vision服务状态",
                "responses": {
                    "200": {
                        "description": "服务状态信息",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "上传图片并进行视觉分析，支持问题询问",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Vision"
                ],
                "summary": "图片视觉分析",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "设备ID",
                        "name": "Device-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "客户端ID",
                        "name": "Client-Id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "图片文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "分析问题",
                        "name": "question",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/vision.VisionAnalysisData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "httptransport.APIResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "ota.Activation": {
            "type": "object",
            "properties": {
                "challenge": {
                    "description": "用于设备认证挑战",
                    "type": "string"
                },
                "code": {
                    "type": "string",
                    "example": "543091"
                },
                "message": {
                    "type": "string",
                    "example": "Anime AI Chat 543091"
                }
            }
        },
        "ota.FirmwareInfo": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string",
                    "example": "/ota_bin/1.2.4.bin"
                },
                "version": {
                    "type": "string",
                    "example": "1.2.4"
                }
            }
        },
        "ota.MQTTInfo": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string",
                    "example": "CGID_test@@@mac@@@client"
                },
                "endpoint": {
                    "type": "string",
                    "example": "mqtt://broker:1883"
                },
                "password": {
                    "type": "string",
                    "example": "randomPwd"
                },
                "publish_topic": {
                    "type": "string",
                    "example": "device-server"
                },
                "subscribe_topic": {
                    "type": "string",
                    "example": "null"
                },
                "username": {
                    "type": "string",
                    "example": "base64string"
                }
            }
        },
        "ota.OTAResponse": {
            "type": "object",
            "properties": {
                "activation": {
                    "$ref": "#/definitions/ota.Activation"
                },
                "firmware": {
                    "$ref": "#/definitions/ota.FirmwareInfo"
                },
                "mqtt": {
                    "$ref": "#/definitions/ota.MQTTInfo"
                },
                "server_time": {
                    "$ref": "#/definitions/ota.ServerTimeInfo"
                },
                "websocket": {
                    "$ref": "#/definitions/ota.WebSocketInfo"
                }
            }
        },
        "ota.ServerTimeInfo": {
            "type": "object",
            "properties": {
                "timestamp": {
                    "type": "integer",
                    "example": 1720065289451
                },
                "timezone_offset": {
                    "type": "integer",
                    "example": 480
                }
            }
        },
        "ota.WebSocketInfo": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string",
                    "example": "wss://your-server/ws"
                }
            }
        },
        "v1.DatabaseConfigInfo": {
            "type": "object",
            "properties": {
                "database": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "v1.DatabaseStatus": {
            "type": "object",
            "properties": {
                "connection": {
                    "description": "connected, disconnected",
                    "type": "string"
                },
                "database": {
                    "type": "string"
                },
                "host": {
                    "type": "string"
                },
                "max_connections": {
                    "type": "integer"
                },
                "open_connections": {
                    "type": "integer"
                },
                "port": {
                    "type": "integer"
                },
                "slow_queries": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "type": {
                    "description": "mysql, postgresql, sqlite",
                    "type": "string"
                }
            }
        },
        "v1.DeviceActivationRequest": {
            "type": "object",
            "required": [
                "activation_code"
            ],
            "properties": {
                "activation_code": {
                    "type": "string"
                },
                "configuration": {
                    "type": "object",
                    "additionalProperties": true
                },
                "device_name": {
                    "type": "string"
                }
            }
        },
        "v1.DeviceActivationResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "device_info": {
                    "$ref": "#/definitions/v1.DeviceInfo"
                },
                "device_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "v1.DeviceInfo": {
            "type": "object",
            "properties": {
                "configuration": {
                    "type": "object",
                    "additionalProperties": true
                },
                "created_at": {
                    "type": "string"
                },
                "device_id": {
                    "type": "string"
                },
                "device_name": {
                    "type": "string"
                },
                "device_type": {
                    "type": "string"
                },
                "firmware": {
                    "$ref": "#/definitions/v1.FirmwareInfo"
                },
                "id": {
                    "type": "integer"
                },
                "is_activated": {
                    "type": "boolean"
                },
                "is_active": {
                    "type": "boolean"
                },
                "last_seen": {
                    "type": "string"
                },
                "location": {
                    "$ref": "#/definitions/v1.DeviceLocation"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "model": {
                    "type": "string"
                },
                "status": {
                    "description": "online, offline, error, unknown",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "v1.DeviceListResponse": {
            "type": "object",
            "properties": {
                "devices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.DeviceInfo"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/v1.Pagination"
                }
            }
        },
        "v1.DeviceLocation": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "altitude": {
                    "type": "number"
                },
                "city": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "province": {
                    "type": "string"
                }
            }
        },
        "v1.DeviceRegistrationRequest": {
            "type": "object",
            "required": [
                "device_id",
                "device_name",
                "device_type"
            ],
            "properties": {
                "device_id": {
                    "type": "string"
                },
                "device_name": {
                    "type": "string"
                },
                "device_type": {
                    "type": "string"
                },
                "location": {
                    "$ref": "#/definitions/v1.DeviceLocation"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "model": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "v1.DeviceStatusRequest": {
            "type": "object",
            "required": [
                "device_id",
                "is_active"
            ],
            "properties": {
                "device_id": {
                    "description": "设备MAC地址",
                    "type": "string"
                },
                "is_active": {
                    "description": "激活状态：true激活，false禁用",
                    "type": "boolean"
                }
            }
        },
        "v1.DeviceStatusResponse": {
            "type": "object",
            "properties": {
                "device_info": {
                    "$ref": "#/definitions/v1.DeviceInfo"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "v1.DeviceUpdateRequest": {
            "type": "object",
            "properties": {
                "configuration": {
                    "type": "object",
                    "additionalProperties": true
                },
                "device_name": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "location": {
                    "$ref": "#/definitions/v1.DeviceLocation"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "v1.FirmwareInfo": {
            "type": "object",
            "properties": {
                "checksum": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "download_count": {
                    "type": "integer"
                },
                "release_date": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "v1.HealthCheck": {
            "type": "object",
            "properties": {
                "details": {},
                "duration": {
                    "description": "毫秒",
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "v1.HealthCheckRequest": {
            "type": "object",
            "properties": {
                "checks": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "timeout": {
                    "description": "超时时间（秒）",
                    "type": "integer"
                }
            }
        },
        "v1.HealthCheckResponse": {
            "type": "object",
            "properties": {
                "checks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.HealthCheckResult"
                    }
                },
                "duration": {
                    "description": "检查耗时（毫秒）",
                    "type": "integer"
                },
                "overall": {
                    "type": "string"
                },
                "status": {
                    "description": "healthy, unhealthy, degraded",
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "v1.HealthCheckResult": {
            "type": "object",
            "properties": {
                "details": {},
                "duration": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "v1.HealthComponent": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "latency": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "v1.Pagination": {
            "type": "object",
            "properties": {
                "has_next": {
                    "type": "boolean"
                },
                "has_prev": {
                    "type": "boolean"
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "v1.Provider": {
            "type": "object",
            "properties": {
                "config": {
                    "type": "object",
                    "additionalProperties": true
                },
                "created_at": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "description": "active, inactive, error",
                    "type": "string"
                },
                "type": {
                    "description": "llm, tts, asr, vllm",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "v1.ProviderConfigRequest": {
            "type": "object",
            "required": [
                "config",
                "name",
                "type"
            ],
            "properties": {
                "config": {
                    "type": "object",
                    "additionalProperties": true
                },
                "enabled": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "v1.ProviderList": {
            "type": "object",
            "properties": {
                "providers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.Provider"
                    }
                }
            }
        },
        "v1.ServerTimeInfo": {
            "type": "object",
            "properties": {
                "current_time": {
                    "type": "string"
                },
                "load": {
                    "type": "number"
                },
                "timezone": {
                    "type": "string"
                },
                "uptime": {
                    "type": "integer"
                }
            }
        },
        "v1.ServiceStatus": {
            "type": "object",
            "properties": {
                "checks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.HealthCheck"
                    }
                },
                "health": {
                    "description": "healthy, unhealthy",
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "description": "running, stopped, error",
                    "type": "string"
                },
                "uptime": {
                    "type": "integer"
                }
            }
        },
        "v1.SystemAdminInfo": {
            "type": "object",
            "properties": {
                "config": {
                    "description": "配置信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.SystemConfigInfo"
                        }
                    ]
                },
                "cpu": {
                    "description": "CPU使用率",
                    "type": "number"
                },
                "disk": {
                    "description": "磁盘使用",
                    "type": "string"
                },
                "load": {
                    "description": "系统负载",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.SystemLoadInfo"
                        }
                    ]
                },
                "logs": {
                    "description": "日志信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.SystemLogsInfo"
                        }
                    ]
                },
                "memory": {
                    "description": "内存使用率",
                    "type": "string"
                },
                "services": {
                    "description": "服务列表",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "v1.SystemBasicInfo": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "系统状态",
                    "type": "string"
                },
                "timestamp": {
                    "description": "时间戳",
                    "type": "string"
                },
                "uptime": {
                    "description": "运行时间（秒）",
                    "type": "integer"
                },
                "version": {
                    "description": "版本号",
                    "type": "string"
                }
            }
        },
        "v1.SystemConfigInfo": {
            "type": "object",
            "properties": {
                "config_path": {
                    "description": "配置文件路径",
                    "type": "string"
                },
                "database": {
                    "description": "数据库配置",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.DatabaseConfigInfo"
                        }
                    ]
                },
                "initialized": {
                    "description": "是否已初始化",
                    "type": "boolean"
                },
                "needs_setup": {
                    "description": "是否需要设置",
                    "type": "boolean"
                }
            }
        },
        "v1.SystemConfigRequest": {
            "type": "object",
            "properties": {
                "setting": {
                    "type": "string"
                },
                "value": {}
            }
        },
        "v1.SystemConfigResponse": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "type": {
                    "description": "string, number, boolean, object",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "string"
                },
                "value": {}
            }
        },
        "v1.SystemHealthInfo": {
            "type": "object",
            "properties": {
                "components": {
                    "description": "组件状态",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.HealthComponent"
                    }
                },
                "overall": {
                    "description": "整体状态",
                    "type": "string"
                },
                "timestamp": {
                    "description": "检查时间",
                    "type": "string"
                }
            }
        },
        "v1.SystemLoadInfo": {
            "type": "object",
            "properties": {
                "cpu": {
                    "description": "CPU负载",
                    "type": "number"
                },
                "disk": {
                    "description": "磁盘负载",
                    "type": "number"
                },
                "memory": {
                    "description": "内存负载",
                    "type": "number"
                },
                "network": {
                    "description": "网络负载",
                    "type": "number"
                }
            }
        },
        "v1.SystemLogsInfo": {
            "type": "object",
            "properties": {
                "count": {
                    "description": "日志数量",
                    "type": "integer"
                },
                "last_log": {
                    "description": "最后日志内容",
                    "type": "string"
                },
                "level": {
                    "description": "日志级别",
                    "type": "string"
                },
                "total_lines": {
                    "description": "总日志行数",
                    "type": "integer"
                }
            }
        },
        "v1.SystemOperationRequest": {
            "type": "object",
            "required": [
                "operation"
            ],
            "properties": {
                "operation": {
                    "description": "操作类型",
                    "type": "string"
                },
                "options": {
                    "description": "操作选项",
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "v1.SystemStatistics": {
            "type": "object",
            "properties": {
                "active_sessions": {
                    "type": "integer"
                },
                "cpu_usage": {
                    "type": "number"
                },
                "disk_usage": {
                    "type": "number"
                },
                "error_requests": {
                    "type": "integer"
                },
                "memory_usage": {
                    "type": "integer"
                },
                "registered_users": {
                    "type": "integer"
                },
                "storage_used": {
                    "type": "integer"
                },
                "success_requests": {
                    "type": "integer"
                },
                "total_requests": {
                    "type": "integer"
                },
                "total_users": {
                    "type": "integer"
                }
            }
        },
        "v1.SystemStatus": {
            "type": "object",
            "properties": {
                "database": {
                    "$ref": "#/definitions/v1.DatabaseStatus"
                },
                "environment": {
                    "type": "string"
                },
                "go_version": {
                    "type": "string"
                },
                "services": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.ServiceStatus"
                    }
                },
                "start_time": {
                    "type": "string"
                },
                "statistics": {
                    "$ref": "#/definitions/v1.SystemStatistics"
                },
                "status": {
                    "type": "string"
                },
                "uptime": {
                    "description": "运行时间（秒）",
                    "type": "integer"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "v1.SystemTimeInfo": {
            "type": "object",
            "properties": {
                "current_time": {
                    "description": "当前时间",
                    "type": "string"
                },
                "timezone": {
                    "description": "时区",
                    "type": "string"
                },
                "uptime": {
                    "description": "运行时间（秒）",
                    "type": "integer"
                }
            }
        },
        "v1.UnifiedSystemInfo": {
            "type": "object",
            "properties": {
                "admin": {
                    "description": "管理员专用",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.SystemAdminInfo"
                        }
                    ]
                },
                "basic": {
                    "description": "普通用户可见",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.SystemBasicInfo"
                        }
                    ]
                },
                "health": {
                    "description": "所有用户可见",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.SystemHealthInfo"
                        }
                    ]
                },
                "time": {
                    "description": "所有用户可见",
                    "allOf": [
                        {
                            "$ref": "#/definitions/v1.SystemTimeInfo"
                        }
                    ]
                }
            }
        },
        "vision.VisionAnalysisData": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "错误信息（失败时）",
                    "type": "string"
                },
                "result": {
                    "description": "分析结果（成功时）",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "请在请求头中添加 Bearer Token，格式为 \"Authorization: Bearer \u003ctoken\u003e\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "小智服务端 API 文档",
	Description:      "小智服务端，包含OTA与Vision等接口",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
